<?php
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function employees_media_link_text_form_editor_media_dialog_alter(array &$form, FormStateInterface $form_state) {
  if (isset($form_state->getUserInput()['editor_object'])) {
    $editor_object = $form_state->getUserInput()['editor_object'];
    $media_embed_element = $editor_object['attributes'];
  } else {
    // Retrieve the user input from form state.
    $media_embed_element = $form_state->get('media_embed_element');
  }

  // Add link text for media entities.
  $media = \Drupal::service('entity.repository')->loadEntityByUuid('media', $media_embed_element['data-entity-uuid']);
  if( empty($media) ) return;
  // Only add link text when the Media is document
  if($media->bundle() == 'document') {
      $form['data-alt-link-text'] = [
        '#type' => 'textfield',
        '#title' => t('Link Text'),
        '#description' => t('Overrides link text if the display mode includes a link to the file.'),
        '#default_value' => $media_embed_element['data-alt-link-text'] ?? '',
        '#maxlength' => 512,
        '#weight' => 1,
        '#parents' => ['attributes', 'data-alt-link-text'],
      ];
  }
}
