name: employees
recipe: pantheon
config:
  framework: drupal8
  site: employees
  id: 7f99fc39-aa02-4ea5-a753-9ea5e2b38435
  index: false
  edge: false
  cache: false
services:
  appserver:
    build_as_root:
      - /bin/sh -c "cp /app/cop_ca_*.crt /usr/local/share/ca-certificates/"
      - update-ca-certificates
    run_as_root:
      - /bin/sh -c "if [ ! -d /var/www/.terminus/plugins/terminus-secrets-plugin ]; then { mkdir -p /var/www/.terminus/plugins; composer create-project -d /var/www/.terminus/plugins pantheon-systems/terminus-secrets-plugin:~1; chown -R www-data:www-data /var/www/.terminus; } fi"
    xdebug: true
    config:
      conf: xdebug.ini
tooling:
  drush:
    description: Run drush commands
    service: appserver
    cmd: drush --root=/app/web
  latest:
    description: Download and import the latest database from Dev
    cmd:
      - appserver: mkdir -p /app/artifacts
      - appserver: echo "Downloading latest database..."
      - appserver: rm -f /app/artifacts/database.tar.gz
      - appserver: terminus backup:get employees.dev --element=database --to=/app/artifacts/database.tar.gz
      - appserver: echo "Importing database..."
      - database: /helpers/sql-import.sh artifacts/database.tar.gz
      - appserver: echo "Clearing cache..."
      - appserver: drush cr -y
  refresh:
    description: Refresh branch by installing Composer dependencies and importing Drupal config, etc. Run after every merge from master.
    cmd:
      - appserver: echo "Installing Composer dependencies..."
      - appserver: composer install -d /app
      - appserver: echo "Clearing cache..."
      - appserver: drush cr -y
      - appserver: echo "Run database updates..."
      - appserver: drush updb -y
      - appserver: echo "Importing Drupal config..."
      - appserver: drush cim -y
      - appserver: echo "Running cron..."
      - appserver: drush core:cron -y
      - appserver: echo "Clearing cache..."
      - appserver: drush cr -y
      # - appserver: echo "Building theme asset files..."
      # - node: npm -C /app/web/themes/custom/cloudy run build:dev
