name: employees
recipe: pantheon
config:
  framework: drupal9
  site: employees
  id: 7f99fc39-aa02-4ea5-a753-9ea5e2b38435
  index: false
  edge: false
  cache: false
  composer_version: 2
services:
  appserver:
    build_as_root:
      - /bin/sh -c "cp /app/cop_ca_*.crt /usr/local/share/ca-certificates/"
      - update-ca-certificates
    run_as_root:
      - /bin/sh -c "if [ ! -d /var/www/.terminus/plugins/terminus-secrets-plugin ]; then { mkdir -p /var/www/.terminus/plugins; composer create-project -d /var/www/.terminus/plugins pantheon-systems/terminus-secrets-plugin:~1; chown -R www-data:www-data /var/www/.terminus; } fi"
    xdebug: false
    config:
      php: xdebug.ini
    overrides:
      environment:
        XDEBUG_MODE:
  node:
    type: node
    overrides:
      environment:
        LANDO_WEBROOT_USER: www-data
        LANDO_WEBROOT_GROUP: www-data
    run_as_root:
      - /bin/sh -c "adduser www-data node"
      - /bin/sh -c "chmod -R 775 /var/www"
    build:
      - echo "Installing Node.js dependencies..."
      - npm -C /app/web/themes/custom/cloudy2 install
tooling:
  drush:
    description: Run drush commands
    service: appserver
    cmd: drush --root=/app/web
  npm:
    description: Run npm commands
    service: node
    cmd: npm -C /app/web/themes/custom/cloudy2
  node:
    description: Run node commands
    service: node
  latest:
    description: Download and import the latest database from Dev
    cmd:
      - appserver: mkdir -p /app/artifacts
      - appserver: echo "Downloading latest dev database..."
      - appserver: rm -f /app/artifacts/database.tar.gz
      - appserver: terminus backup:get employees.dev --element=database --to=/app/artifacts/database.tar.gz
      - appserver: echo "Importing database..."
      - database: /helpers/sql-import.sh artifacts/database.tar.gz
#      - appserver: echo "Sanitizing database..."
#      - appserver: drush sql-query "drop temporary table if exists to_update; create temporary table to_update select distinct uid, name from users_field_data U left outer join user__roles R on U.uid = R.entity_id where R.roles_target_id is null or 'administrator' not in (select roles_target_id from users_field_data U2 left outer join user__roles R2 on U2.uid = R2.entity_id where U2.name = U.name); update users_field_data U inner join to_update UP on U.uid = UP.uid set U.pass = '', U.mail = concat('user+', UP.uid, '@localhost.localdomain'), U.init = concat('user+', UP.uid, '@localhost.localdomain') where UP.name <> 'Oliver Outsider' and UP.name <> 'Marty Member' and UP.name <> 'Ally Admin'; drop temporary table to_update;"
#      - appserver: echo "Truncating webforms and logs..."
#      - appserver: drush sql-query "truncate table webform_submission; truncate table webform_submission_data; truncate table webform_submission_log;"
#      - appserver: drush sql-query "truncate table watchdog;"
      - appserver: echo "Clearing cache..."
      - appserver: drush cr -y
  refresh:
    description: Refresh branch by installing Composer dependencies and importing Drupal config, etc. Run after every merge from master.
    cmd:
      - appserver: date +"%T"
      - appserver: /bin/bash -c "if [[ \$(composer install --dry-run -d /app --no-interaction 2>&1 | grep -oPc 'Removing drupal/\w+') -gt 0 ]]; then { echo Composer is about to remove one or more modules... Let\'s disable them in Drupal first.; for module in \$(composer install --dry-run -d /app --no-interaction 2>&1 | grep -oP 'Removing drupal/\K\w+'); do { echo Disabling \$module...; drush pmu \$module -y;} done } fi"
      - appserver: echo "=====Timestamp===== Starting Drupal Config Refresh"
      - appserver: date +"%T"
      - appserver: echo "Installing Composer dependencies..."
      - appserver: composer install -d /app
      - appserver: date +"%T"
      - appserver: echo "Clearing cache..."
      - appserver: drush cr -y
      - appserver: date +"%T"
      - appserver: echo "Run drush updb -y..."
      - appserver: drush updb -y
      - appserver: date +"%T"
      - appserver: echo "Run drush cim -y..."
      - appserver: drush cim -y
      - appserver: date +"%T"
      - appserver: echo "Clearing cache..."
      - appserver: drush cr -y
      - appserver: date +"%T"
      - appserver: echo "=====Timestamp===== Drupal Config Refresh Done"
      - appserver: date +"%T"
      # TODO: [POWR-3430] Add theme build to employees .lando.yml
  cupex:
    description: Composer update, database update, and config export to get a clean module or theme update
    cmd:
      - appserver: echo "Updating Composer dependencies..."
      - appserver: composer update
      - appserver: echo "Run database updates..."
      - appserver: drush updb -y
      - appserver: echo "Exporting Drupal config..."
      - appserver: drush cex -y
      # - appserver: echo "Building theme asset files..."
      # - node: npm -C /app/web/themes/custom/cloudy run build:dev
  xdebug-on:
    service: appserver
    description: Enable xdebug for nginx.
    cmd: docker-php-ext-enable xdebug && pkill -o -USR2 php-fpm && echo "Enabling xdebug"
    user: root
  xdebug-off:
    service: appserver
    description: Disable xdebug for nginx.
    cmd: rm /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && pkill -o -USR2 php-fpm && echo "Disabling xdebug"
    user: root