theme: cloudy2
defaults:
  sender: sendgrid_integration
  formatter: mime_mail
_core:
  default_config_hash: IhwTepsVwtbtbcT5GzQKhCXDCRvbk3MNkWqPiuiZ10s
modules:
  sendgrid_integration:
    none:
      formatter: sendgrid_integration
      sender: sendgrid_integration
  employees:
    none:
      formatter: mime_mail
