_core:
  default_config_hash: IhwTepsVwtbtbcT5GzQKhCXDCRvbk3MNkWqPiuiZ10s
theme: cloudy2
defaults:
  sender: test_mail_collector
  formatter: mime_mail
modules:
  sendgrid_integration:
    none:
      sender: test_mail_collector
      formatter: sendgrid_integration
  employees:
    none:
      formatter: mime_mail
