_core:
  default_config_hash: ttd8HXcqwSjGgp-fWA3gUA8q4TNvXB0a72pkFlnF56g
hotlink: true
origin: 'https://employees.portland.gov'
origin_dir: sites/default/files
use_imagecache_root: true
verify: true
excluded_extensions: ''
