adding:
  description: 'Currently configured with a local Solr server on a Lando environment.'
  backend_config:
    connector: standard
    connector_config:
      scheme: http
      host: solr
      port: 8983
      path: /
      core: lando
      index_timeout: 5
      optimize_timeout: 10
      skip_schema_check: false
removing:
  dependencies:
    module:
      - search_api_pantheon
  description: 'Currently configured with a Pantheon Solr server on a Pantheon environment.'
  backend_config:
    connector: pantheon
    connector_config:
      index_timeout: 60
      optimize_timeout: 60
      skip_schema_check: true
