login_path: /user/login
_core:
  default_config_hash: ZKVq7lpyGFQf-SCuj_Ng2yLPD24rKHxz-TzGQxBjLl4
paths: "~/openid-connect/azure\r\n~/sites/default/files/**\r\n*"
message: 'Welcome to the beta version of the new City of Portland employee intranet website. City employees with a ROSE or PTLD account may log in.'
