_core:
  default_config_hash: ZKVq7lpyGFQf-SCuj_Ng2yLPD24rKHxz-TzGQxBjLl4
paths:
  - ~/openid-connect/azure
  - '~/sites/default/files/**'
  - '~/webform/css/*'
  - '~/webform/javascript/*'
  - /admin
  - '/admin/*'
  - /my-groups
  - /my-content
  - /my-media
  - '*/edit'
  - '*/members'
  - '*/nodes'
  - '*/media'
  - '*/node/create'
  - '*/media/create'
  - '*/revisions'
  - '*/revisions/*/view'
  - '*/latest'
  - /directory
  - /user
  - '/user/*'
  - '*/join'
login_path: /user/login
message: ''
