_core:
  default_config_hash: QqhYOhPHWGDL9oSnXSdIaYuEA3hHLDNjYouaWatEXc8
allowed_roles:
  authenticated: authenticated
  publisher: publisher
  bts_catalog: bts_catalog
  content_lead: content_lead
  administrator: '0'
