_core:
  default_config_hash: M2IHVLIoE4E1qYW00XgY7Zn0npfJv5AFxZR49rqqJfA
collapse_all: 0
variant: ckeditor_accordion_variant_pgov
langcode: en
keep_rows_open: 1
animate_accordion_toggle: 0
open_tabs_with_hash: 0
