verbose: true
types:
  block_content: {  }
  contact_message: {  }
  content_moderation_state: {  }
  crop: {  }
  file: {  }
  group_config_wrapper: {  }
  group_relationship: {  }
  group:
    '*': '*'
  group_content_menu: {  }
  media: {  }
  node:
    '*': '*'
  path_alias: {  }
  redirect: {  }
  search_api_task: {  }
  taxonomy_term: {  }
  user: {  }
  webform_submission: {  }
  menu_link_content: {  }
types_translation_lock: {  }
form_op_lock:
  block_content:
    mode: 0
    values: {  }
  contact_message:
    mode: 0
    values: {  }
  content_moderation_state:
    mode: 0
    values: {  }
  crop:
    mode: 0
    values: {  }
  file:
    mode: 0
    values: {  }
  group_config_wrapper:
    mode: 0
    values: {  }
  group_relationship:
    mode: 0
    values: {  }
  group:
    mode: 1
    values:
      edit: edit
  group_content_menu:
    mode: 0
    values: {  }
  media:
    mode: 0
    values: {  }
  node:
    mode: 1
    values:
      edit: edit
  path_alias:
    mode: 0
    values: {  }
  redirect:
    mode: 0
    values: {  }
  search_api_task:
    mode: 0
    values: {  }
  taxonomy_term:
    mode: 0
    values: {  }
  user:
    mode: 0
    values: {  }
  webform_submission:
    mode: 0
    values: {  }
  menu_link_content:
    mode: 0
    values: {  }
timeout: 259200
