verbose: true
types:
  group:
    '*': '*'
  node:
    '*': '*'
types_translation_lock: {  }
form_op_lock:
  group:
    mode: 1
    values:
      edit: edit
  node:
    mode: 1
    values:
      edit: edit
timeout: 259200
