_core:
  default_config_hash: o4bYR9ZupWb3AsOIizTUG4g-nu1mdJqA59UB7QT-ifQ
definitions:
  contact__site_page:
    menu_name: footer
    parent: ''
    weight: 0
    expanded: false
    enabled: true
  masquerade__unmasquerade:
    menu_name: account
    parent: ''
    weight: -50
    expanded: false
    enabled: false
  standard__front_page:
    menu_name: main
    parent: ''
    weight: -50
    expanded: false
    enabled: true
  'admin_toolbar_tools__extra_links:view__files':
    menu_name: admin
    parent: system.admin_content
    weight: 1
    expanded: false
    enabled: true
  'admin_toolbar_tools__extra_links:media_page':
    menu_name: admin
    parent: system.admin_content
    weight: 2
    expanded: false
    enabled: true
