_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  action: 0
  add_content_by_bundle: 0
  admin_toolbar: 0
  admin_toolbar_links_access_filter: 0
  admin_toolbar_search: 0
  admin_toolbar_tools: 0
  allowed_formats: 0
  anonymous_login: 0
  anonymous_login_extranet: 0
  automated_cron: 0
  block: 0
  block_content: 0
  block_exclude_pages: 0
  breakpoint: 0
  bulk_user_registration: 0
  ckeditor: 0
  ckeditor_acr: 0
  components: 0
  config: 0
  config_filter: 0
  config_split: 0
  contact: 0
  content_moderation: 0
  contextual: 0
  crop: 0
  csv_serialization: 0
  ctools: 0
  datalayer: 0
  datetime: 0
  datetime_range: 0
  dblog: 0
  diff: 0
  dynamic_page_cache: 0
  easy_breadcrumb: 0
  editor: 0
  embed: 0
  employees: 0
  employees_media_link_text: 0
  employees_migrations: 0
  entity: 0
  entity_usage: 0
  environment_indicator: 0
  eva: 0
  facets: 0
  field: 0
  field_group: 0
  field_permissions: 0
  field_states_ui: 0
  field_ui: 0
  file: 0
  file_mdm: 0
  file_mdm_exif: 0
  file_mdm_font: 0
  filter: 0
  fontawesome: 0
  gnode: 0
  google_tag: 0
  group: 0
  group_notifications: 0
  group_views_join_link: 0
  groupmedia: 0
  help: 0
  image: 0
  image_effects: 0
  imagemagick: 0
  inline_entity_form: 0
  inline_form_errors: 0
  jquery_ui: 0
  key: 0
  language: 0
  layout_builder: 0
  layout_builder_restrictions: 0
  layout_builder_restrictions_by_region: 0
  layout_builder_styles: 0
  layout_discovery: 0
  layout_library: 0
  link: 0
  linkit: 0
  mailsystem: 0
  masquerade: 0
  media: 0
  media_entity_download: 0
  media_library: 0
  media_remote: 0
  menu_breadcrumb: 0
  menu_ui: 0
  migrate: 0
  migrate_plus: 0
  migrate_source_csv: 0
  migrate_source_ui: 0
  migrate_tools: 0
  mimemail: 0
  moderation_sidebar: 0
  mysql: 0
  node: 0
  openid_connect: 0
  openid_connect_windows_aad: 0
  options: 0
  pantheon_advanced_page_cache: 0
  path: 0
  path_alias: 0
  portland_groups: 0
  portland_openid_connect: 0
  portland_revision_helper: 0
  portland_zendesk: 0
  quick_node_clone: 0
  rabbit_hole: 0
  realname: 0
  redirect: 0
  redirect_404: 0
  redis: 0
  remove_http_headers: 0
  responsive_image: 0
  rest: 0
  rh_node: 0
  samlauth: 0
  scheduler: 0
  scheduler_content_moderation_integration: 0
  search_api: 0
  search_api_autocomplete: 0
  search_api_pantheon: 0
  search_api_pantheon_admin: 0
  search_api_solr: 0
  search_api_solr_autocomplete: 0
  seckit: 0
  select2: 0
  sendgrid_integration: 0
  serialization: 0
  settings_tray: 0
  show_email: 0
  simple_gmap: 0
  smart_date: 0
  smart_trim: 0
  sophron: 0
  structure_sync: 0
  subpathauto: 0
  system: 0
  taxonomy: 0
  telephone: 0
  text: 0
  toc_js: 0
  token: 0
  toolbar: 0
  toolbar_menu: 0
  tour: 0
  transliterate_filenames: 0
  twig_tools: 0
  twig_tweak: 0
  update: 0
  user: 0
  variationcache: 0
  views_bulk_edit: 0
  views_bulk_operations: 0
  views_data_export: 0
  views_ui: 0
  webform: 0
  webform_ui: 0
  workflows: 0
  extlink: 1
  menu_link_content: 1
  pathauto: 1
  externalauth: 10
  views: 10
  standard: 1000
theme:
  stable: 0
  classy: 0
  radix: 0
  claro: 0
  westy: 0
profile: standard
