module:
  admin_toolbar: 0
  admin_toolbar_links_access_filter: 0
  admin_toolbar_tools: 0
  anonymous_login: 0
  bg_image_formatter: 0
  blazy: 0
  block: 0
  block_content: 0
  breakpoint: 0
  ckeditor: 0
  components: 0
  config: 0
  config_filter: 0
  config_split: 0
  consumers: 0
  contact: 0
  content_moderation: 0
  contextual: 0
  crop: 0
  ctools: 0
  datetime: 0
  dblog: 0
  diff: 0
  editor: 0
  embed: 0
  entity_block: 0
  entity_browser: 0
  entity_browser_block: 0
  entity_embed: 0
  entity_reference: 0
  facets: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  fixed_block_content: 0
  hal: 0
  help: 0
  history: 0
  image: 0
  image_widget_crop: 0
  inline_entity_form: 0
  jsonapi: 0
  key: 0
  language: 0
  layout_builder: 0
  layout_builder_restrictions: 0
  layout_builder_st: 0
  layout_builder_styles: 0
  layout_discovery: 0
  layout_library: 0
  libraries: 0
  lightning_contact_form: 0
  lightning_core: 0
  lightning_install: 0
  lightning_layout: 0
  lightning_map_block: 0
  lightning_scheduler: 0
  link: 0
  media: 0
  menu_ui: 0
  metatag: 0
  moderation_dashboard: 0
  moderation_sidebar: 0
  node: 0
  openapi: 0
  openapi_ui: 0
  openapi_ui_redoc: 0
  openapi_ui_swagger: 0
  openid_connect: 0
  options: 0
  page_cache: 0
  page_manager: 0
  page_manager_ui: 0
  panels: 0
  path: 0
  path_alias: 0
  permissions_by_term: 0
  portland_openid_connect: 0
  quickedit: 0
  rdf: 0
  redirect: 0
  redirect_404: 0
  schemata: 0
  schemata_json_schema: 0
  search_api: 0
  search_api_autocomplete: 0
  search_api_db: 0
  search_api_solr: 0
  serialization: 0
  shortcut: 0
  simple_gmap: 0
  simple_oauth: 0
  simple_oauth_extras: 0
  system: 0
  taxonomy: 0
  text: 0
  time_field: 0
  token: 0
  toolbar: 0
  user: 0
  video_embed_field: 0
  video_embed_media: 0
  views_infinite_scroll: 0
  views_ui: 0
  workflows: 0
  contact_storage: 1
  menu_link_content: 1
  pathauto: 1
  views: 10
  lightning: 1000
theme:
  stable: 0
  classy: 0
  claro: 0
  radix: 0
  cloudy2: 0
profile: lightning
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
