add_page_meta: true
output_terms: true
output_fields: false
group: false
lib_helper: false
entity_meta:
  created: '0'
  langcode: '0'
  name: '0'
  status: '0'
  uid: '0'
  uuid: '0'
  vid: '0'
enable_ia: false
ia_depth: 3
ia_category_primary: primaryCategory
ia_category_sub: subCategory
vocabs:
  citywide_contract: '0'
  group_ad_name_list: '0'
  org_type: '0'
  tags: '0'
  topics: '0'
expose_user_details: ''
expose_user_details_roles:
  authenticated: authenticated
  publisher: publisher
  administrator: administrator
  content_lead: '0'
current_user_meta:
  roles: roles
  name: '0'
  mail: '0'
  created: '0'
  access: '0'
expose_user_details_fields: true
entity_title: entityTitle
entity_type: entityType
entity_bundle: entityBundle
entity_identifier: entityId
group_label: groupLabel
drupal_language: drupalLanguage
drupal_country: drupalCountry
site_name: siteName
key_replacements:
  - ''
_core:
  default_config_hash: N67AkcKPlikWJbwxABv6MSMpGuXe36qWZfH88pEzeqc
