_core:
  default_config_hash: AXUBMTvVtpcNp0jKjDaWjSHqMy6HjuUf7j4yVbXgazI
local_task_enabled_entity_types:
  - group
  - media
  - node
  - taxonomy_term
track_enabled_source_entity_types:
  - group
  - group_relationship
  - media
  - node
  - redirect
  - taxonomy_term
track_enabled_target_entity_types:
  - group
  - media
  - node
  - taxonomy_term
track_enabled_plugins:
  - entity_embed
  - entity_reference
  - html_link
  - link
  - linkit
  - media_embed
track_enabled_base_fields: false
site_domains:
  - dev-employees.pantheonsite.io
  - employees.lndo.site
  - employees.portland.gov
  - test-employees.pantheonsite.io
edit_warning_message_entity_types: {  }
delete_warning_message_entity_types:
  - group
  - media
  - node
  - taxonomy_term
usage_controller_items_per_page: 25
