_core:
  default_config_hash: vOaSYBgSyTzn8_p0MSY8B-ygp9V0Nc6qnX0vy9KYGeo
langcode: en
extlink_use_external_js_file: false
extlink_exclude_admin_routes: true
extlink_target: false
extlink_target_no_override: false
extlink_title_no_override: false
extlink_nofollow: false
extlink_noreferrer: true
extlink_follow_no_override: false
extlink_subdomains: false
extlink_alert: false
extlink_alert_text: 'This link will take you to an external web site. We are not responsible for their content.'
extlink_hide_icons: false
extlink_additional_link_classes: ''
extlink_additional_mailto_classes: ''
extlink_additional_tel_classes: ''
extlink_exclude: ''
extlink_include: ''
extlink_exclude_noreferrer: ''
extlink_class: ext
extlink_label: '(link is external)'
extlink_img_class: false
extlink_css_exclude: ''
extlink_css_include: ''
extlink_css_explicit: ''
extlink_mailto_class: mailto
extlink_mailto_label: '(link sends email)'
extlink_tel_class: '0'
extlink_tel_label: '(link is a phone number)'
extlink_use_font_awesome: true
extlink_font_awesome_classes:
  links: 'fa fa-external-link-alt'
  mailto: 'fa fa-envelope'
  tel: 'fa fa-phone'
extlink_icon_placement: append
extlink_prevent_orphan: false
whitelisted_domains:
  - employees.portland.gov
