admin_toolbar: 1.27.0
anonymous_login: 1.1.0
bg_image_formatter: 1.6.0
blazy: 1.0.0-rc4
block: 8.7.1
block_content: 8.7.1
bootstrap_datepicker: 1.0.0-beta2
breakpoint: 8.7.1
ckeditor: 8.7.1
components: 1.1.0
config: 8.7.1
config_filter: 1.4.0
config_split: 1.4.0
consumers: 1.9.0
contact: 8.7.1
contact_storage: 1.0.0-beta9
content_moderation: 8.7.1
contextual: 8.7.1
crop: 2.0.0-rc1
ctools: 3.0.0
datetime: 8.7.1
dblog: 8.7.1
diff: 1.0.0-rc2
dropzonejs: 2.0.0-alpha3
editor: 8.7.1
embed: 1.0.0
entity_block: 1.0.0-beta1
entity_browser: 2.1.0
entity_browser_block: 1.0.0
entity_embed: 1.0.0-beta2
entity_reference: 8.7.1
facets: 1.4.0
field: 8.7.1
field_ui: 8.7.1
file: 8.7.1
filter: 8.7.1
help: 8.7.1
history: 8.7.1
image: 8.7.1
image_widget_crop: 2.2.0
inline_entity_form: 1.0.0-rc1
jsonapi: 0.0.0
key: 1.8.0
language: 8.7.5
layout_builder: 8.7.1
layout_builder_restrictions: 1.5.0
layout_builder_st: 1.0.0-alpha1
layout_discovery: 8.7.1
layout_library: 1.0.0-alpha2
libraries: 3.0.0-alpha1
lightning: 4.000.0
lightning_api: 4.1.0
lightning_banner_block: 2.0.0
lightning_contact_form: 4.1.0
lightning_core: 4.1.0
lightning_install: 4.000.0
lightning_landing_page: 2.0.0
lightning_layout: 2.0.0
lightning_map_block: 2.0.0
lightning_media: 3.8.0
lightning_media_audio: 3.8.0
lightning_media_bulk_upload: 3.8.0
lightning_media_document: 3.8.0
lightning_media_image: 3.8.0
lightning_media_instagram: 3.8.0
lightning_media_slideshow: 3.8.0
lightning_media_twitter: 3.8.0
lightning_media_video: 3.8.0
lightning_page: 4.1.0
lightning_roles: 4.1.0
lightning_scheduler: 3.6.0
lightning_search: 4.1.0
lightning_workflow: 3.6.0
link: 8.7.1
media: 8.7.1
media_entity_instagram: 2.0.0-alpha2
media_entity_twitter: 2.0.0-alpha2
media_library: 8.7.1
menu_link_content: 8.7.1
menu_ui: 8.7.1
metatag: 1.8.0
moderation_dashboard: 1.0.0-beta1
moderation_sidebar: 1.1.0
node: 8.7.1
openapi: 1.0.0-beta2
openapi_ui: 1.0.0-rc1
openapi_ui_redoc: 1.0.0-rc2
openapi_ui_swagger: 1.0.0-rc3
openid_connect: 1.0.0-beta5
options: 8.7.1
page_cache: 8.7.1
page_manager: 4.0.0-beta3
panels: 4.3.0
path: 8.7.1
pathauto: 1.4.0
permissions_by_term: 2.10.0
portland_openid_connect: 0.1.0
quickedit: 8.7.1
rdf: 8.7.1
redirect: 1.4.0
redirect_404: 1.4.0
schemata: 1.0.0-alpha7
schemata_json_schema: 1.0.0-alpha7
search_api: 1.13.0
search_api_autocomplete: 1.2.0
search_api_db: 1.13.0
search_api_solr: 3.1.0
serialization: 8.7.1
shortcut: 8.7.1
simple_gmap: 1.4.0
simple_oauth: 3.16.0
simple_oauth_extras: 3.16.0
slick: 1.1.0
slick_entityreference: 1.1.0
system: 8.7.1
taxonomy: 8.7.1
text: 8.7.1
time_field: 1.12.0
token: 1.5.0
toolbar: 8.7.1
user: 8.7.1
video_embed_field: 2.1.0
video_embed_media: 2.1.0
views: 8.7.1
views_infinite_scroll: 1.5.0
views_ui: 8.7.1
workflows: 8.7.1
