format: full_html
name: ''
mail: ''
linkonly: false
textonly: false
sitestyle: true
simple_address: false
preserve_class: false
advanced:
  incoming: false
  key: ''
_core:
  default_config_hash: rLKGzzC9TqjbEZiBoiyMpOSyZgldADa5SzvbA2gQDxE
