_core:
  default_config_hash: rLKGzzC9TqjbEZiBoiyMpOSyZgldADa5SzvbA2gQDxE
name: ''
mail: ''
simple_address: false
sitestyle: true
textonly: false
linkonly: false
format: full_html
preserve_class: false
advanced:
  incoming: false
  key: ''
