enabled: windows_aad
settings:
  redirect_url: ''
  client_id: 7cec2858-72a2-4a6a-bf26-336fd0c4e67e
  client_secret: null
  enable_single_sign_out: 0
  authorization_endpoint_wa: 'https://login.microsoftonline.com/636d7808-73c9-41a7-97aa-8c4733642141/oauth2/v2.0/authorize'
  token_endpoint_wa: 'https://login.microsoftonline.com/636d7808-73c9-41a7-97aa-8c4733642141/oauth2/v2.0/token'
  map_ad_groups_to_roles: 0
  group_mapping:
    method: '0'
    mappings: ''
    strict: 0
  userinfo_graph_api_wa: '2'
  userinfo_endpoint_wa: 'https://example.com/oauth2/UserInfo'
  userinfo_graph_api_use_other_mails: 0
  userinfo_update_email: 1
  hide_email_address_warning: 0
  override_name: '1'
_core:
  default_config_hash: zKCZci5IzwHTf3xysPemd4YQsOPQ4rce90VKNpk7PeI
