enabled: true
settings:
  redirect_url: ''
  client_id: ''
  client_secret: ''
  client_id_display: ''
  client_secret_display: ''
  authorization_endpoint: 'https://login.microsoftonline.com/common/oauth2/authorize'
  token_endpoint: 'https://login.microsoftonline.com/common/oauth2/token'
  userinfo_endpoint: 'https://graph.windows.net/me?api-version=1.6'
_core:
  default_config_hash: b5Nmh4U49pSzYWhpp-sT_EopsYtYKQ_Jf9xEuvw9ddE
