_core:
  default_config_hash: LNYrEZMNvotD7ZS_X0b59tq3Jyl-f5lNMUOZWTLuC9A
headers_to_remove:
  - X-Generator
  - X-Powered-By
  - Server
dependencies:
  enforced:
    module:
      - remove_http_headers
