_core:
  default_config_hash: oDGEkhP0h5rXXqlDplxeBDre0goLigOJupHKMDMwcqM
login_menu_item_title: ''
logout_menu_item_title: ''
login_redirect_url: ''
logout_redirect_url: ''
error_redirect_url: ''
error_throw: false
local_login_saml_error: false
logout_different_user: false
drupal_login_roles:
  authenticated: '0'
  publisher: '0'
  bts_catalog: '0'
  311_support_agent: '0'
  311_lead: '0'
  content_lead: '0'
  administrator: '0'
sp_entity_id: employees.portland.gov
sp_name_id_format: ''
sp_x509_certificate: 'file:/files/private/sp.crt'
sp_new_certificate: ''
sp_private_key: 'file:/files/private/sp.key'
metadata_valid_secs: 60
metadata_cache_http: false
idp_entity_id: 'http://sts.portlandoregon.gov/adfs/services/trust'
idp_single_sign_on_service: 'https://sts.portlandoregon.gov/adfs/ls/'
idp_single_log_out_service: 'https://sts.portlandoregon.gov/adfs/ls/'
idp_change_password_service: 'https://sts.portlandoregon.gov/adfs/ls/'
idp_certs:
  - 'file:/files/private/idp.crt'
idp_cert_encryption: ''
unique_id_attribute: 'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress'
map_users: false
map_users_name: false
map_users_mail: true
map_users_roles:
  publisher: publisher
  bts_catalog: bts_catalog
  311_support_agent: 311_support_agent
  311_lead: 311_lead
  content_lead: content_lead
  administrator: administrator
create_users: false
sync_name: false
sync_mail: false
user_name_attribute: ''
user_mail_attribute: 'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress'
request_set_name_id_policy: true
strict: true
security_metadata_sign: true
security_authn_requests_sign: true
security_logout_requests_sign: true
security_logout_responses_sign: true
security_nameid_encrypt: false
security_signature_algorithm: ''
security_encryption_algorithm: ''
security_messages_sign: false
security_assertions_signed: false
security_assertions_encrypt: false
security_nameid_encrypted: false
security_want_name_id: true
security_request_authn_context: true
security_lowercase_url_encoding: true
security_logout_reuse_sigs: false
security_allow_repeat_attribute_name: false
debug_display_error_details: false
debug_log_in: false
debug_log_saml_in: false
debug_log_saml_out: false
debug_phpsaml: false
use_proxy_headers: false
use_base_url: true
