blocks:
  -
    info: 'Prompt anonymous user to log in'
    langcode: en
    uuid: 29c58e51-adf5-4358-a9c1-b902dc9477c3
    bundle: basic
    revision_id: null
    rev_id_current: null
    fields:
      body:
        -
          value: '<div class="card mb-4"><h2 class="card-header">Customize your experience</h2><div class="card-body"><p class="card-text">Users with a City of Portland network account may log in to personalize their content.</p><p><a class="btn btn-primary" href="/user/login">Log in</a></p></div></div>'
          summary: ''
          format: full_html
  -
    info: 'Feedback link'
    langcode: en
    uuid: d397a46d-b25c-4254-bc22-26d5860b8280
    bundle: basic
    revision_id: null
    rev_id_current: null
    fields:
      body:
        -
          value: "<p>See something we could improve on&nbsp;this page?&nbsp;<a href=\"/feedback\">Give website feedback</a>.</p>\r\n"
          summary: ''
          format: basic_html
