taxonomies:
  bts_application_exception:
    -
      vid: bts_application_exception
      tid: '418'
      langcode: en
      name: 'No'
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: f432bc67-f995-424c-9d96-ea7f553d4c0c
    -
      vid: bts_application_exception
      tid: '419'
      langcode: en
      name: 'Not allowed'
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: 5ec8be08-b6a2-444f-9e71-8683e373c311
    -
      vid: bts_application_exception
      tid: '420'
      langcode: en
      name: 'Yes'
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: f87d7a05-dc6b-4458-ba16-205f40866e20
  bts_business_capability:
    -
      vid: bts_business_capability
      tid: '422'
      langcode: en
      name: Analytics
      description__value: "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed interdum turpis et dolor tempus, quis sagittis lorem suscipit. Fusce sed turpis porta, pharetra augue quis, malesuada purus. Ut aliquet pretium purus, ac molestie augue suscipit vitae. Ut pellentesque elementum mauris, non convallis enim tincidunt eget. Maecenas ac velit quis ante tristique fermentum ut sit amet lorem. Morbi elementum suscipit elementum. Phasellus in nulla vitae tellus ultrices dictum. Donec erat lectus, dictum vel urna sed, maximus pharetra metus. Sed odio arcu, semper in nibh egestas, vulputate maximus risus.</p>\r\n"
      description__format: basic_html
      weight: '0'
      parent: '421'
      uuid: 40956249-aae0-47fb-9644-b17053b8de54
    -
      vid: bts_business_capability
      tid: '421'
      langcode: en
      name: 'Business Intelligence'
      description__value: "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed interdum turpis et dolor tempus, quis sagittis lorem suscipit. Fusce sed turpis porta, pharetra augue quis, malesuada purus. Ut aliquet pretium purus, ac molestie augue suscipit vitae. Ut pellentesque elementum mauris, non convallis enim tincidunt eget. Maecenas ac velit quis ante tristique fermentum ut sit amet lorem. Morbi elementum suscipit elementum. Phasellus in nulla vitae tellus ultrices dictum. Donec erat lectus, dictum vel urna sed, maximus pharetra metus. Sed odio arcu, semper in nibh egestas, vulputate maximus risus.</p>\r\n"
      description__format: basic_html
      weight: '4'
      parent: '0'
      uuid: 1d77a909-70bd-45b7-ac8a-3eae7990cdd4
    -
      vid: bts_business_capability
      tid: '474'
      langcode: en
      name: 'Content Management'
      description__value: "<p>Content Management includes Content Authoring, Content Review and Approval, Tagging and Aggregation, Content Publishing and Delivery and<br />\r\nSyndication Management.</p>\r\n"
      description__format: basic_html
      weight: '0'
      parent: '0'
      uuid: 635968d0-b325-4082-b361-57a973d86b5b
    -
      vid: bts_business_capability
      tid: '475'
      langcode: en
      name: Customer
      description__value: "<p>Members of the distribution chain (e.g., channel and alliance partners, resellers, agents, brokers, and dealers) and other third parties that the City supports via operations and service delivery to customers</p>\r\n"
      description__format: basic_html
      weight: '0'
      parent: '470'
      uuid: 7d01306e-cc37-4d72-a8ee-190568e831d5
    -
      vid: bts_business_capability
      tid: '423'
      langcode: en
      name: Discovery
      description__value: "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed interdum turpis et dolor tempus, quis sagittis lorem suscipit. Fusce sed turpis porta, pharetra augue quis, malesuada purus. Ut aliquet pretium purus, ac molestie augue suscipit vitae. Ut pellentesque elementum mauris, non convallis enim tincidunt eget. Maecenas ac velit quis ante tristique fermentum ut sit amet lorem. Morbi elementum suscipit elementum. Phasellus in nulla vitae tellus ultrices dictum. Donec erat lectus, dictum vel urna sed, maximus pharetra metus. Sed odio arcu, semper in nibh egestas, vulputate maximus risus.</p>\r\n"
      description__format: basic_html
      weight: '1'
      parent: '421'
      uuid: 5effff82-b157-4fed-841f-8f0a1db0512c
    -
      vid: bts_business_capability
      tid: '476'
      langcode: en
      name: 'External Partner'
      description__value: "<p>\"External members of the distribution chain (e.g., channel and alliance partners, resellers, agents, brokers, and dealers) and other third parties that support operations and service delivery to an organization’s customers; includes performance<br />\r\nevaluation of partners, if necessary\"</p>\r\n"
      description__format: basic_html
      weight: '0'
      parent: '470'
      uuid: 071f1c70-8b4d-4386-b51f-bfe7eb912c31
    -
      vid: bts_business_capability
      tid: '477'
      langcode: en
      name: Internal
      description__value: "<p>Internal members of the distribution chain (e.g., channel and alliance partners, resellers, agents, brokers, and dealers) and other third parties that support operations and service delivery to an organization’s customers; includes performance<br />\r\nevaluation of partners, if necessary</p>\r\n"
      description__format: basic_html
      weight: '0'
      parent: '470'
      uuid: a9499c05-478b-4491-a4c9-b6584c1b2c6e
    -
      vid: bts_business_capability
      tid: '424'
      langcode: en
      name: 'Knowledge Capture'
      description__value: "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed interdum turpis et dolor tempus, quis sagittis lorem suscipit. Fusce sed turpis porta, pharetra augue quis, malesuada purus. Ut aliquet pretium purus, ac molestie augue suscipit vitae. Ut pellentesque elementum mauris, non convallis enim tincidunt eget. Maecenas ac velit quis ante tristique fermentum ut sit amet lorem. Morbi elementum suscipit elementum. Phasellus in nulla vitae tellus ultrices dictum. Donec erat lectus, dictum vel urna sed, maximus pharetra metus. Sed odio arcu, semper in nibh egestas, vulputate maximus risus.</p>\r\n"
      description__format: basic_html
      weight: '2'
      parent: '421'
      uuid: d7200188-e24b-4cdc-bf40-76d5937d09a7
    -
      vid: bts_business_capability
      tid: '473'
      langcode: en
      name: 'Mapping Geospatial'
      description__value: "<p>Provide for the representation of mapping and geospatial information through the use of attributes such as zip code, country code, elevation, natural features and other spatial measures.</p>\r\n"
      description__format: basic_html
      weight: '0'
      parent: '0'
      uuid: bf81c1d3-ddf7-4192-ba6f-c6c25506cb31
    -
      vid: bts_business_capability
      tid: '472'
      langcode: en
      name: 'Public Comment Tracking'
      description__value: "<p>Public Comment Tracking involves the activities of soliciting, maintaining, and responding to public comments regarding proposed regulations.</p>\r\n"
      description__format: basic_html
      weight: '0'
      parent: '0'
      uuid: 1ade1a0d-20be-4a0b-935e-97d497563994
    -
      vid: bts_business_capability
      tid: '471'
      langcode: en
      name: 'Records Management and Retention'
      description__value: "<p>Management of Government Records involves the management and stewardship of a type of information by the federal government in order to facilitate communication and information archival. This classification and taxonomic processes that links logical data and information sets.&nbsp; This also includes the retention of documents and other information as per retention requirements</p>\r\n"
      description__format: basic_html
      weight: '0'
      parent: '0'
      uuid: 602c53c4-67ac-4e8b-a7c2-2b3b3edd76bd
    -
      vid: bts_business_capability
      tid: '470'
      langcode: en
      name: 'Relationship Management'
      description__value: "<p>Provides a framework to promote the effective collaboration between an organization and its business partners</p>\r\n"
      description__format: basic_html
      weight: '0'
      parent: '0'
      uuid: 05c240fe-e85f-4fe6-aa18-dc1327351eba
    -
      vid: bts_business_capability
      tid: '426'
      langcode: en
      name: 'Strategic Planning'
      description__value: "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed interdum turpis et dolor tempus, quis sagittis lorem suscipit. Fusce sed turpis porta, pharetra augue quis, malesuada purus. Ut aliquet pretium purus, ac molestie augue suscipit vitae. Ut pellentesque elementum mauris, non convallis enim tincidunt eget. Maecenas ac velit quis ante tristique fermentum ut sit amet lorem. Morbi elementum suscipit elementum. Phasellus in nulla vitae tellus ultrices dictum. Donec erat lectus, dictum vel urna sed, maximus pharetra metus. Sed odio arcu, semper in nibh egestas, vulputate maximus risus.</p>\r\n"
      description__format: basic_html
      weight: '5'
      parent: '0'
      uuid: a73dc29d-7589-44b3-9c2a-4b87047fbebd
    -
      vid: bts_business_capability
      tid: '425'
      langcode: en
      name: Visualization
      description__value: "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed interdum turpis et dolor tempus, quis sagittis lorem suscipit. Fusce sed turpis porta, pharetra augue quis, malesuada purus. Ut aliquet pretium purus, ac molestie augue suscipit vitae. Ut pellentesque elementum mauris, non convallis enim tincidunt eget. Maecenas ac velit quis ante tristique fermentum ut sit amet lorem. Morbi elementum suscipit elementum. Phasellus in nulla vitae tellus ultrices dictum. Donec erat lectus, dictum vel urna sed, maximus pharetra metus. Sed odio arcu, semper in nibh egestas, vulputate maximus risus.</p>\r\n"
      description__format: basic_html
      weight: '3'
      parent: '421'
      uuid: 4904b649-e96b-49fb-9d77-035d07a83f9b
  bts_business_priority:
    -
      vid: bts_business_priority
      tid: '430'
      langcode: en
      name: 'Business Essential - Deadlines'
      description__value: null
      description__format: null
      weight: '0'
      parent: '482'
      uuid: a2c2e89c-af01-40d6-89c9-48b796187ee3
    -
      vid: bts_business_priority
      tid: '431'
      langcode: en
      name: 'Business Essential - Enterprise Solution / Migration / Revenue Generating'
      description__value: "<p>Test</p>\r\n"
      description__format: basic_html
      weight: '1'
      parent: '482'
      uuid: 13ee19f0-a64f-4747-be9a-f542cddf9951
    -
      vid: bts_business_priority
      tid: '432'
      langcode: en
      name: 'Business Essential No Deadlines'
      description__value: null
      description__format: null
      weight: '2'
      parent: '482'
      uuid: 4c09dba7-3aad-4743-aec5-4613f6e6d3d2
    -
      vid: bts_business_priority
      tid: '482'
      langcode: en
      name: 'Business Essentials'
      description__value: null
      description__format: null
      weight: '5'
      parent: '0'
      uuid: de32fda8-d61e-453b-aa6e-fd866b991094
    -
      vid: bts_business_priority
      tid: '436'
      langcode: en
      name: 'Capital Improvement Program Related'
      description__value: null
      description__format: null
      weight: '13'
      parent: '0'
      uuid: 772af157-1946-4637-80c8-cdcedf4bfc4e
    -
      vid: bts_business_priority
      tid: '437'
      langcode: en
      name: Mandated
      description__value: null
      description__format: null
      weight: '12'
      parent: '0'
      uuid: 8f1943e8-e853-44a9-926b-7355b93e1066
    -
      vid: bts_business_priority
      tid: '481'
      langcode: en
      name: 'Mission Critical'
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: 873b9844-30a9-422b-83f2-71429be28cbf
    -
      vid: bts_business_priority
      tid: '427'
      langcode: en
      name: 'Mission Critical - Deadlines'
      description__value: null
      description__format: null
      weight: '0'
      parent: '481'
      uuid: adfe5a2b-090e-4801-b3d2-71f2d374678c
    -
      vid: bts_business_priority
      tid: '428'
      langcode: en
      name: 'Mission Critical - Enterprise Solution / Migration / Revenue Generating'
      description__value: null
      description__format: null
      weight: '1'
      parent: '481'
      uuid: 6b3d0153-b564-410e-922e-94b40f6d7e07
    -
      vid: bts_business_priority
      tid: '429'
      langcode: en
      name: 'Mission Critical - No Deadlines'
      description__value: null
      description__format: null
      weight: '2'
      parent: '481'
      uuid: a0e0d425-50e4-4360-b98c-8d498cdc9565
    -
      vid: bts_business_priority
      tid: '438'
      langcode: en
      name: 'Non Serviceable'
      description__value: null
      description__format: null
      weight: '15'
      parent: '0'
      uuid: ab6207f3-9a7b-4d6d-97cb-a4f4ff19989e
    -
      vid: bts_business_priority
      tid: '483'
      langcode: en
      name: 'Normal Business Operations'
      description__value: null
      description__format: null
      weight: '10'
      parent: '0'
      uuid: e4bda9a3-5880-41b6-aadb-6dc1754e9419
    -
      vid: bts_business_priority
      tid: '434'
      langcode: en
      name: 'Normal Business Operations - Enterprise Migration / Revenue Generating'
      description__value: null
      description__format: null
      weight: '1'
      parent: '483'
      uuid: 19e9ddbe-11f9-4e13-8c90-9978c139196b
    -
      vid: bts_business_priority
      tid: '433'
      langcode: en
      name: 'Normal Business Operations Deadlines'
      description__value: null
      description__format: null
      weight: '0'
      parent: '483'
      uuid: 59a2c088-e8db-4e33-b4f8-db2759cb6213
    -
      vid: bts_business_priority
      tid: '435'
      langcode: en
      name: 'Normal Business Operations No Deadlines'
      description__value: null
      description__format: null
      weight: '2'
      parent: '483'
      uuid: cd932fbc-a9c2-40e2-8d71-3023557087cd
    -
      vid: bts_business_priority
      tid: '439'
      langcode: en
      name: Servicable
      description__value: null
      description__format: null
      weight: '14'
      parent: '0'
      uuid: b9bd7ddb-a3c4-46c7-8acb-47d02b4ac8ab
  bureaus:
    -
      vid: bureaus
      tid: '444'
      langcode: en
      name: BHR
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: a4010892-12a4-4153-9a48-3d0eb20d6c36
    -
      vid: bureaus
      tid: '445'
      langcode: en
      name: BOEC
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: 3f081eb4-e17a-4601-8d43-84e38f31ff2f
    -
      vid: bureaus
      tid: '446'
      langcode: en
      name: BPS
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: 34caed35-b5a7-4871-b41a-4840cf2ecb01
    -
      vid: bureaus
      tid: '447'
      langcode: en
      name: BRFS/Revenue
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: 251100a9-8305-45da-a82c-9d996de0dc28
    -
      vid: bureaus
      tid: '449'
      langcode: en
      name: BTS
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: adaec1ae-201f-4eed-a83e-59e50d3b8e9e
    -
      vid: bureaus
      tid: '450'
      langcode: en
      name: Citywide
      description__value: "<p>Applications used accross ALL Bureaus</p>\r\n"
      description__format: basic_html
      weight: '0'
      parent: '0'
      uuid: a9383d5a-53d9-458e-9a91-80275a8d8c37
    -
      vid: bureaus
      tid: '451'
      langcode: en
      name: DAM
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: de900afe-b7ac-4a9f-a307-f9696e08869a
    -
      vid: bureaus
      tid: '448'
      langcode: en
      name: NTS
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: 50834737-04f0-4a61-b37c-f06a31229e65
    -
      vid: bureaus
      tid: '478'
      langcode: en
      name: OCCL
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: 01003753-768e-4d11-81f6-6a11ef1f6a72
    -
      vid: bureaus
      tid: '452'
      langcode: en
      name: PHB
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: 8c4772de-6042-45f4-97f9-b236a32fdcaa
    -
      vid: bureaus
      tid: '479'
      langcode: en
      name: Water
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: 75c6c9fe-9c25-4919-82ed-afa8f8b7f447
  cloud_service_type:
    -
      vid: cloud_service_type
      tid: '459'
      langcode: en
      name: IaaS
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: 67b520e0-4c38-42a0-9716-d98e22e711c4
    -
      vid: cloud_service_type
      tid: '460'
      langcode: en
      name: PaaS
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: 51865ded-3d4e-4698-b58d-1228c9e4f0ed
    -
      vid: cloud_service_type
      tid: '461'
      langcode: en
      name: SaaS
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: f879992e-4494-449e-a263-1a251a278bac
  hosting_environment:
    -
      vid: hosting_environment
      tid: '462'
      langcode: en
      name: Cloud
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: 646706d2-26ef-4b6b-8ed8-cf86f39bcde2
    -
      vid: hosting_environment
      tid: '463'
      langcode: en
      name: Hybrid
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: 47887383-9b22-42f7-a47c-c9359049aa0d
    -
      vid: hosting_environment
      tid: '464'
      langcode: en
      name: 'On Premise'
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: bb483470-8b99-48b0-9254-1c50ba083855
  support_model:
    -
      vid: support_model
      tid: '465'
      langcode: en
      name: Bureau
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: 6b3a3cbf-b813-487e-bffa-ef5b9592a3fa
    -
      vid: support_model
      tid: '466'
      langcode: en
      name: Full
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: caf552bb-da0d-4a5c-8046-5e43edb64163
    -
      vid: support_model
      tid: '467'
      langcode: en
      name: Limited
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: 58eabb96-7927-49b8-86bd-84abcce1c9be
    -
      vid: support_model
      tid: '468'
      langcode: en
      name: 'Not allowed'
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: 16f61c2f-f8b7-4fc3-82fa-25c4ed9f1558
    -
      vid: support_model
      tid: '469'
      langcode: en
      name: User
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: a01f1c43-44fd-42d8-a1b3-76b0a66408a5
