taxonomies:
  contract_category:
    -
      vid: contract_category
      tid: '251'
      langcode: en
      name: Aggregates
      description__value: null
      description__format: null
      weight: '0'
      parent: '241'
      uuid: b35e40ad-f60c-42b5-89fd-dac675e7f68e
    -
      vid: contract_category
      tid: '249'
      langcode: en
      name: 'American Sign Language (ASL)'
      description__value: null
      description__format: null
      weight: '0'
      parent: '240'
      uuid: ef0e390d-f8a1-4c22-83d3-0f91d558db16
    -
      vid: contract_category
      tid: '269'
      langcode: en
      name: 'Annual Supply of Fuel'
      description__value: null
      description__format: null
      weight: '0'
      parent: '244'
      uuid: fa2343ec-8d31-4426-9f6a-1b5ac5adb80e
    -
      vid: contract_category
      tid: '261'
      langcode: en
      name: 'Arborist Services'
      description__value: null
      description__format: null
      weight: '0'
      parent: '243'
      uuid: 357996b2-20e3-4670-b84c-540804de2752
    -
      vid: contract_category
      tid: '262'
      langcode: en
      name: 'Armored Car Transport Services'
      description__value: null
      description__format: null
      weight: '1'
      parent: '243'
      uuid: 41862adf-b9cf-42c1-8d36-c397b234bf7e
    -
      vid: contract_category
      tid: '263'
      langcode: en
      name: 'Auction Services'
      description__value: null
      description__format: null
      weight: '2'
      parent: '243'
      uuid: 3a28cc9c-8a64-4d71-b9f3-5cb4b7a0628c
    -
      vid: contract_category
      tid: '268'
      langcode: en
      name: 'Audit Services'
      description__value: null
      description__format: null
      weight: '3'
      parent: '243'
      uuid: 20f4ca59-a6de-46a3-9dd6-7de4312b8432
    -
      vid: contract_category
      tid: '246'
      langcode: en
      name: 'Building Maintenance and Supplies'
      description__value: null
      description__format: null
      weight: '19'
      parent: '0'
      uuid: fa5cf2cb-16ef-4d4a-99c5-ec532d3a911b
    -
      vid: contract_category
      tid: '252'
      langcode: en
      name: 'Bulk Mixed Concrete'
      description__value: null
      description__format: null
      weight: '1'
      parent: '241'
      uuid: 890bb93a-dc94-46c7-a9d9-c0bd0b3e75a3
    -
      vid: contract_category
      tid: '247'
      langcode: en
      name: Clothing
      description__value: null
      description__format: null
      weight: '24'
      parent: '0'
      uuid: f07b0e3d-957f-4eaa-91f7-0a83a21d764a
    -
      vid: contract_category
      tid: '295'
      langcode: en
      name: 'Community Engagement Liaison'
      description__value: null
      description__format: null
      weight: '0'
      parent: '248'
      uuid: 69da9027-e7d6-4bea-b4e0-8b4b6036e813
    -
      vid: contract_category
      tid: '241'
      langcode: en
      name: Construction
      description__value: null
      description__format: null
      weight: '33'
      parent: '0'
      uuid: b53639bc-5566-4f38-adf6-ca3159865bcc
    -
      vid: contract_category
      tid: '258'
      langcode: en
      name: 'Contaminated Media Disposal'
      description__value: null
      description__format: null
      weight: '0'
      parent: '242'
      uuid: 6164bcdb-9acb-4296-bf05-53de2eeee056
    -
      vid: contract_category
      tid: '280'
      langcode: en
      name: 'Data Communications Products and Services'
      description__value: null
      description__format: null
      weight: '0'
      parent: '246'
      uuid: c02a7fec-c7cf-4482-b445-48c658d7ee0b
    -
      vid: contract_category
      tid: '264'
      langcode: en
      name: 'Document Shredding'
      description__value: null
      description__format: null
      weight: '4'
      parent: '243'
      uuid: 1ed46eb8-fe78-4ec9-9ce4-e3c1ed80dba3
    -
      vid: contract_category
      tid: '278'
      langcode: en
      name: 'Electrical Parts and Supplies'
      description__value: null
      description__format: null
      weight: '1'
      parent: '246'
      uuid: 98fd2bb8-7dca-4bf4-ba01-74f06f674047
    -
      vid: contract_category
      tid: '242'
      langcode: en
      name: Environment
      description__value: null
      description__format: null
      weight: '46'
      parent: '0'
      uuid: becbb8d6-dd01-4d23-8ae6-3c3dad001068
    -
      vid: contract_category
      tid: '302'
      langcode: en
      name: 'Federal Compliance'
      description__value: null
      description__format: null
      weight: '0'
      parent: '268'
      uuid: 506d8f01-e76d-475b-98a1-d11d4f053853
    -
      vid: contract_category
      tid: '254'
      langcode: en
      name: 'Fencing Materials and Services'
      description__value: null
      description__format: null
      weight: '2'
      parent: '241'
      uuid: d7370b47-9ed4-4019-9fa2-9af5827b3bf7
    -
      vid: contract_category
      tid: '299'
      langcode: en
      name: Financial
      description__value: null
      description__format: null
      weight: '1'
      parent: '268'
      uuid: 1ead80ee-eb5f-4bef-827d-25eba6bc853b
    -
      vid: contract_category
      tid: '303'
      langcode: en
      name: Fraud
      description__value: null
      description__format: null
      weight: '2'
      parent: '268'
      uuid: e8b4a3c9-ee16-49c7-b55a-9de818adb26f
    -
      vid: contract_category
      tid: '259'
      langcode: en
      name: 'Hazardous Waste Cleanup'
      description__value: null
      description__format: null
      weight: '1'
      parent: '242'
      uuid: 6d7796c7-3007-4288-ab33-c84d50f759dd
    -
      vid: contract_category
      tid: '282'
      langcode: en
      name: 'HVAC Equipment and Services'
      description__value: null
      description__format: null
      weight: '2'
      parent: '246'
      uuid: 4aa7c850-f970-4d06-ac88-252bcdb7fc3a
    -
      vid: contract_category
      tid: '270'
      langcode: en
      name: 'Industrial Equipment'
      description__value: null
      description__format: null
      weight: '1'
      parent: '244'
      uuid: 235c55fb-136a-4873-967b-fc483bc27452
    -
      vid: contract_category
      tid: '292'
      langcode: en
      name: 'Industrial Garments'
      description__value: null
      description__format: null
      weight: '0'
      parent: '247'
      uuid: f0fd4f72-7d91-4b08-bfc6-5a679d7c160f
    -
      vid: contract_category
      tid: '272'
      langcode: en
      name: 'Industrial MRO Supplies'
      description__value: null
      description__format: null
      weight: '2'
      parent: '244'
      uuid: bca3b86e-61c1-486e-9d98-2d03979c1472
    -
      vid: contract_category
      tid: '271'
      langcode: en
      name: 'Industrial Safety Products'
      description__value: null
      description__format: null
      weight: '3'
      parent: '244'
      uuid: fdaf398c-cbb6-4b6c-ba4f-bed556732b82
    -
      vid: contract_category
      tid: '244'
      langcode: en
      name: 'Industrial Supplies and Equipment'
      description__value: null
      description__format: null
      weight: '48'
      parent: '0'
      uuid: d73ebd47-a9c0-4a34-80e0-7739ba115926
    -
      vid: contract_category
      tid: '301'
      langcode: en
      name: 'Information Technology'
      description__value: null
      description__format: null
      weight: '3'
      parent: '268'
      uuid: 8aaee211-8e0d-4de8-a651-4b1467b93f75
    -
      vid: contract_category
      tid: '283'
      langcode: en
      name: 'Janitorial Supplies and Services'
      description__value: null
      description__format: null
      weight: '3'
      parent: '246'
      uuid: 71bdde7d-0f04-4654-90e9-f9a486a0d4ee
    -
      vid: contract_category
      tid: '240'
      langcode: en
      name: 'Language and Translation Services'
      description__value: null
      description__format: null
      weight: '52'
      parent: '0'
      uuid: 80405cd8-36f3-4ffb-b47f-852185b45fde
    -
      vid: contract_category
      tid: '291'
      langcode: en
      name: 'Laundry Services'
      description__value: null
      description__format: null
      weight: '1'
      parent: '247'
      uuid: 28eb2691-beb3-45c9-81a6-bfec737bea17
    -
      vid: contract_category
      tid: '279'
      langcode: en
      name: 'Lighting Supplies'
      description__value: null
      description__format: null
      weight: '4'
      parent: '246'
      uuid: cf3a735c-2484-46b1-aa7d-503287225e2c
    -
      vid: contract_category
      tid: '255'
      langcode: en
      name: 'Lumber Products and Building Supplies'
      description__value: null
      description__format: null
      weight: '3'
      parent: '241'
      uuid: fd455c23-8f39-433a-bc08-e3c42f171f03
    -
      vid: contract_category
      tid: '273'
      langcode: en
      name: 'Medical and Industrial Gases'
      description__value: null
      description__format: null
      weight: '4'
      parent: '244'
      uuid: 8b726e68-0ef8-4f69-aeb6-7c0c2b5e61cf
    -
      vid: contract_category
      tid: '248'
      langcode: en
      name: Miscellaneous
      description__value: null
      description__format: null
      weight: '56'
      parent: '0'
      uuid: 7c39173e-392a-4e31-9a26-5a294d2f6a2b
    -
      vid: contract_category
      tid: '266'
      langcode: en
      name: 'Moving, Installation, Deinstallation and Storage Services'
      description__value: null
      description__format: null
      weight: '5'
      parent: '243'
      uuid: f8561309-75b4-4862-b814-c31a1e8c0f1b
    -
      vid: contract_category
      tid: '260'
      langcode: en
      name: 'Natural Area Habitat Restoration'
      description__value: null
      description__format: null
      weight: '2'
      parent: '242'
      uuid: 1cc3c149-a9bd-4e85-b442-e2d0d97f61d7
    -
      vid: contract_category
      tid: '274'
      langcode: en
      name: 'Office Furniture'
      description__value: null
      description__format: null
      weight: '0'
      parent: '245'
      uuid: cbafadaa-e51a-4924-a9d1-be977f347bec
    -
      vid: contract_category
      tid: '245'
      langcode: en
      name: 'Office Supplies and Equipment'
      description__value: null
      description__format: null
      weight: '57'
      parent: '0'
      uuid: a759814f-6ec8-4cf2-98ae-8ffa759ab3fe
    -
      vid: contract_category
      tid: '284'
      langcode: en
      name: 'On-Call Electrical Services'
      description__value: null
      description__format: null
      weight: '5'
      parent: '246'
      uuid: 8f99cb23-5ac5-4f1e-a26d-7e1a45c4f493
    -
      vid: contract_category
      tid: '285'
      langcode: en
      name: 'On-Call Mechanical Services'
      description__value: null
      description__format: null
      weight: '6'
      parent: '246'
      uuid: 8c0cb260-3fc1-4807-b64f-fa295d4b1f46
    -
      vid: contract_category
      tid: '286'
      langcode: en
      name: 'Paint, Coatings, and Related Supplies'
      description__value: null
      description__format: null
      weight: '7'
      parent: '246'
      uuid: 112d41c2-6688-41b0-96ab-dc70e3fbdae4
    -
      vid: contract_category
      tid: '300'
      langcode: en
      name: Performance
      description__value: null
      description__format: null
      weight: '4'
      parent: '268'
      uuid: c5c4f738-4fa6-4848-9350-c3913700586b
    -
      vid: contract_category
      tid: '265'
      langcode: en
      name: 'Pest Management Services'
      description__value: null
      description__format: null
      weight: '6'
      parent: '243'
      uuid: fb08209d-cb2f-4afd-9145-b1f634867125
    -
      vid: contract_category
      tid: '287'
      langcode: en
      name: 'Plumbing Supplies'
      description__value: null
      description__format: null
      weight: '8'
      parent: '246'
      uuid: de94ba5c-c38b-42c6-877d-314f0042e200
    -
      vid: contract_category
      tid: '296'
      langcode: en
      name: 'Portable Restroom Services'
      description__value: null
      description__format: null
      weight: '1'
      parent: '248'
      uuid: 8f640c8d-c4d1-46e5-8b75-2c36e9889a66
    -
      vid: contract_category
      tid: '256'
      langcode: en
      name: 'Power Tools Sales and Service'
      description__value: null
      description__format: null
      weight: '4'
      parent: '241'
      uuid: 9162a395-1991-48f6-8a73-053bfcacc431
    -
      vid: contract_category
      tid: '243'
      langcode: en
      name: 'Professional Services'
      description__value: null
      description__format: null
      weight: '60'
      parent: '0'
      uuid: e200d0c3-2ed7-457c-b4c5-7ad4758d5513
    -
      vid: contract_category
      tid: '297'
      langcode: en
      name: 'Public Safety and Emergency Preparedness Equipment'
      description__value: null
      description__format: null
      weight: '2'
      parent: '248'
      uuid: 48e1d694-87ad-462a-9960-2edee0187474
    -
      vid: contract_category
      tid: '293'
      langcode: en
      name: 'Rain Wear'
      description__value: null
      description__format: null
      weight: '2'
      parent: '247'
      uuid: 62fa855b-df89-4610-b0a5-aa0b24168f2f
    -
      vid: contract_category
      tid: '288'
      langcode: en
      name: 'Renewable Energy Certificates'
      description__value: null
      description__format: null
      weight: '9'
      parent: '246'
      uuid: 9e5ea53c-ea83-4509-bcc3-ce0d58c1de2f
    -
      vid: contract_category
      tid: '304'
      langcode: en
      name: 'Risk Assessment'
      description__value: null
      description__format: null
      weight: '5'
      parent: '268'
      uuid: ca58c0e0-ce8f-4212-8987-ed1f2fab6f77
    -
      vid: contract_category
      tid: '257'
      langcode: en
      name: 'Road Striping Paint'
      description__value: null
      description__format: null
      weight: '5'
      parent: '241'
      uuid: bc01369f-c3b9-4b2c-8bbc-6e0d6bbb9043
    -
      vid: contract_category
      tid: '289'
      langcode: en
      name: 'Roofing and Building Envelope Services'
      description__value: null
      description__format: null
      weight: '10'
      parent: '246'
      uuid: 41e30f94-969c-4d69-9cd0-8d0b2864fb78
    -
      vid: contract_category
      tid: '281'
      langcode: en
      name: 'Security Products and Services'
      description__value: null
      description__format: null
      weight: '12'
      parent: '246'
      uuid: fb9c1f5e-2464-48a3-a544-9db8a1b6cc0a
    -
      vid: contract_category
      tid: '290'
      langcode: en
      name: 'Snow and Ice Management'
      description__value: null
      description__format: null
      weight: '11'
      parent: '246'
      uuid: a05f6920-f0f4-4848-9f41-7510fa10c325
    -
      vid: contract_category
      tid: '275'
      langcode: en
      name: 'Space Optimization and Furniture'
      description__value: null
      description__format: null
      weight: '1'
      parent: '245'
      uuid: aad57d58-1ede-4a23-9977-acb6ff0d6751
    -
      vid: contract_category
      tid: '276'
      langcode: en
      name: 'Surplus Disposition'
      description__value: null
      description__format: null
      weight: '2'
      parent: '245'
      uuid: 2fed59a2-a68d-4190-97bf-6bbec289ed25
    -
      vid: contract_category
      tid: '294'
      langcode: en
      name: 'T-shirts and Custom Printed Apparel'
      description__value: null
      description__format: null
      weight: '3'
      parent: '247'
      uuid: cd5f7016-8105-49df-9259-cc0e92fcd292
    -
      vid: contract_category
      tid: '267'
      langcode: en
      name: 'Temporary Staffing Services'
      description__value: null
      description__format: null
      weight: '7'
      parent: '243'
      uuid: 66272761-a86c-4398-b391-268c22c58d8c
    -
      vid: contract_category
      tid: '253'
      langcode: en
      name: 'Traffic Signals'
      description__value: null
      description__format: null
      weight: '6'
      parent: '241'
      uuid: ab8a770f-7542-4320-889b-9d8298602ef6
    -
      vid: contract_category
      tid: '277'
      langcode: en
      name: 'Vendor Managed Printer Services'
      description__value: null
      description__format: null
      weight: '3'
      parent: '245'
      uuid: 7b964a69-11c3-4110-9147-b823aa6796a4
    -
      vid: contract_category
      tid: '250'
      langcode: en
      name: 'Video Interpretation Services'
      description__value: null
      description__format: null
      weight: '1'
      parent: '240'
      uuid: 508a2585-9bca-4bf5-8d0c-6c2d66785992
    -
      vid: contract_category
      tid: '298'
      langcode: en
      name: 'Wood Chips and Bark Mulch'
      description__value: null
      description__format: null
      weight: '3'
      parent: '248'
      uuid: 9b4cb768-afde-453e-ad7e-4e834fa1128b
  contract_type:
    -
      vid: contract_type
      tid: '306'
      langcode: en
      name: 'Flexible Services'
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: 0c1974e9-7ed2-4cce-8405-012342048c7e
    -
      vid: contract_type
      tid: '305'
      langcode: en
      name: 'Price Agreement'
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: 4e1284a0-3b58-4d07-a93f-fb79afed56cf
