blocks:
  -
    info: 'Prompt anonymous user to log in'
    langcode: en
    uuid: 29c58e51-adf5-4358-a9c1-b902dc9477c3
    bundle: basic
    revision_id: null
    rev_id_current: null
    fields:
      body:
        -
          value: '<div class="card mb-4"><div class="card-header"><h2 class="my-1">Customize your experience</h2></div><div class="card-body"><p class="card-text">Users with a City of Portland network account may log in to personalize their content.</p><p><a class="btn btn-primary" href="/user/login">Log in</a></p></div></div>'
          summary: ''
          format: full_html
  -
    info: 'Feedback link'
    langcode: en
    uuid: d397a46d-b25c-4254-bc22-26d5860b8280
    bundle: basic
    revision_id: null
    rev_id_current: null
    fields:
      body:
        -
          value: "<p>See something we could improve on&nbsp;this page?&nbsp;<a href=\"/feedback\">Give website feedback</a>.</p>\r\n"
          summary: ''
          format: basic_html
taxonomies:
  org_type:
    -
      vid: org_type
      tid: '648'
      langcode: en
      name: 'Affinity Groups'
      description__value: "<p>Affinity groups are usually committees or employee-led organizations that have been recognized by human resources for their value in helping employees connect.</p>\r\n"
      description__format: basic_html
      weight: '4'
      parent: '0'
      uuid: 359a3a49-a544-46ab-ae51-c3eac0ef3db3
    -
      vid: org_type
      tid: '649'
      langcode: en
      name: 'Citywide Groups'
      description__value: "<p><em>Information, news, and events from citywide portals are automatically feature on the homepage. This content is meant for all employees regardless of bureau.</em></p>\r\n"
      description__format: basic_html
      weight: '0'
      parent: '0'
      uuid: 29822c69-7347-4a23-8650-6ceb72cb4dfa
    -
      vid: org_type
      tid: '650'
      langcode: en
      name: Committees
      description__value: null
      description__format: null
      weight: '3'
      parent: '0'
      uuid: c88b87ed-e73c-438e-9301-1a7b2ce1809c
    -
      vid: org_type
      tid: '645'
      langcode: en
      name: 'Commonly Followed Citywide Groups'
      description__value: "<p>Some citywide information is dependent upon your role as an employee. You may choose to follow a group because you frequently use their services (Fleet, Facilities, Procurement, etc.) or because your job duties require you to use particular documentation to do your job (City Web Editors, Council Authors, etc.).</p>\r\n"
      description__format: basic_html
      weight: '1'
      parent: '0'
      uuid: 30401b89-863e-4716-804a-5c16906019c0
    -
      vid: org_type
      tid: '644'
      langcode: en
      name: 'Office/Bureau Employee Portals'
      description__value: "<p>Offices and bureaus, as well as their child divisions and programs, will soon be automatically assigned to an employee based on their network account groups. If an employee wants or needs to follow another bureaus news and events, they can “join to follow” that group.</p>\r\n"
      description__format: basic_html
      weight: '2'
      parent: '0'
      uuid: 2975d081-7bb6-4288-9a8e-f7df0078a81d
    -
      vid: org_type
      tid: '646'
      langcode: en
      name: Programs
      description__value: "<p>Programs are city structures that might be cross-bureau in nature.</p>\r\n"
      description__format: basic_html
      weight: '5'
      parent: '0'
      uuid: c3b9dc79-97e4-4307-8077-efce99a6fca6
    -
      vid: org_type
      tid: '2025'
      langcode: en
      name: Projects
      description__value: "<p>Collaboration group for projects foreseen to eventually complete</p>\r\n"
      description__format: basic_html
      weight: '6'
      parent: '0'
      uuid: 559d0a03-c8db-40c7-92e1-6efafb74796a
    -
      vid: org_type
      tid: '647'
      langcode: en
      name: Teams
      description__value: "<p>Team groups can be created for collaboration. These will usually be private groups that do not show up in search unless you are a member, but may occasionally be available to all employees for those that want to join and follow the work of a team.</p>\r\n"
      description__format: basic_html
      weight: '7'
      parent: '0'
      uuid: 1106f9aa-8bb3-47db-a265-52d211d6311d
  topics:
    -
      vid: topics
      tid: '980'
      langcode: en
      name: 'Benefits and Wellness'
      description__value: "<p>Links to key resources for employees</p>\r\n"
      description__format: basic_html
      weight: '0'
      parent: '0'
      uuid: 83050b36-9101-4979-b881-c40f510ee595
      field_homepage:
        -
          value: '1'
    -
      vid: topics
      tid: '981'
      langcode: en
      name: 'City Operations Guide'
      description__value: "<p>Everyday sustainability tips and tricks for working at the City</p>\r\n"
      description__format: basic_html
      weight: '0'
      parent: '0'
      uuid: c76765dd-4f1c-4675-b9fc-8cbc822fb1c7
      field_homepage:
        -
          value: '1'
    -
      vid: topics
      tid: '976'
      langcode: en
      name: 'Employee Services'
      description__value: "<p>Access SAP portal for your time sheet, leave balances, and CityLearner; log onto your Office365 account from home; access your W-2</p>\r\n"
      description__format: basic_html
      weight: '0'
      parent: '0'
      uuid: a693e485-c1fb-46f4-9db9-0b72e37522dc
      field_homepage:
        -
          value: '1'
    -
      vid: topics
      tid: '977'
      langcode: en
      name: 'Forms Libraries'
      description__value: "<p>Internal forms from various bureaus</p>\r\n"
      description__format: basic_html
      weight: '0'
      parent: '0'
      uuid: 5cba8448-f572-4d35-8bce-6c6c54485022
      field_homepage:
        -
          value: '1'
    -
      vid: topics
      tid: '978'
      langcode: en
      name: 'Policies and Procedures'
      description__value: "<p>Important info for work at the City</p>\r\n"
      description__format: basic_html
      weight: '0'
      parent: '0'
      uuid: 10a3383c-ef3c-4cd7-a0b6-5ee1b045a51e
      field_homepage:
        -
          value: '1'
    -
      vid: topics
      tid: '2132'
      langcode: en
      name: 'Quick Links'
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: f5265615-fa97-4a80-b45d-12dc3b8c85ac
      field_homepage:
        -
          value: '0'
    -
      vid: topics
      tid: '979'
      langcode: en
      name: 'Training and Development'
      description__value: "<p>Information about employee training and workforce development opportunities</p>\r\n"
      description__format: basic_html
      weight: '0'
      parent: '0'
      uuid: 89b48cdf-aad9-46b4-9049-7dbaac87b146
      field_homepage:
        -
          value: '1'
