<?php
/**
 * @file
 * Theme functions
 */

// Include all files from the includes directory.
$includes_path = dirname(__FILE__) . '/includes/*.inc';
foreach (glob($includes_path) as $filename) {
  require_once dirname(__FILE__) . '/includes/' . basename($filename);
}


function cloudy2_preprocess_media(&$vars) {
  $test = $vars;
}

function cloudy2_preprocess_filter_caption(&$vars) {
  $test = $vars;
}